collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.4559613
color:
  saturation: 1
  brandStrength: 0.9070892
  lightness: 1
  brandColors:
    - '#3A2F27'
    - '#A48053'
    - '#BDAC99'
    - '#D9E9FA'
    - '#5D7FA3'
  rhythmicContrast: 0
layout_spectrum: 0.3141783
name: ratmentor.com
