collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.264769
  brandStrength: 0.9070892
  lightness: 0.7427498
  brandColors:
    - '#3A2F27'
    - '#A48053'
    - '#BDAC99'
    - '#D9E9FA'
    - '#5D7FA3'
  rhythmicContrast: 0.2765843
typography_spectrum: 0.4398496
layout_spectrum: 0
name: ratmentor.com
